---
- name: Ensure we are using pkgng
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use pkgng as a package manager."
  when: ansible_pkg_mgr != "pkgng"

- name: Uninstall VirtualBox Guest Additions from pkgng
  block:
    - name: Update pkg repository catalog
      ansible.builtin.command: pkg update
      changed_when: false # Currently, the pkg module does not support update_cache and cache_valid_time.
      become: true

    - name: Remove VirtualBox Guest Additions if it is installed
      community.general.pkgng:
        name: "{{ package }}"
        state: absent
      loop: "{{ virtualbox_guest_distro_pkgs }}"
      loop_control:
        loop_var: package
      become: true
