---
- name: Uninstall current installation of VirtualBox Guest Additions
  block:
    - name: Uninstall VirtualBox Guest Additions from source
      ansible.builtin.include_tasks: noauto_uninstall_source.yml
      when: virtualbox_guest_installed_version is defined and virtualbox_guest_installed_version != ""
