---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Install virtualbox guest additions dependencies via apk
  block:
    - name: Update apk cache
      community.general.apk:
        update_cache: true
      changed_when: false # The apk module currently does not support cache_valid_time.
      become: true

    - name: Ensure virtualbox guest additions dependencies are installed
      community.general.apk:
        name: "{{ package }}"
        state: present
      loop: "{{ virtualbox_guest_dep_pkgs }}"
      loop_control:
        loop_var: package
      become: true
